development:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: youtube_downloader_development

test:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: youtube_downloader_test

production:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: youtube_downloader_production
